Dummy PR
knikure/sagemaker-python-sdk pull request #2
Opened 2022-08-04 23:06 UTC by knikure

*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md) doc
- [ ] I certify that the changes I am introducing will be backword compatible, and I have discussed concerns about this, if any, with the Python SDK team
- [ ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/sagemaker-python-sdk/blob/master/CONTRIBUTING.md#committing-your-change)
- [ ] I have passed the region in to all S3 and STS clients that I've initialized as part of this change.
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst) and [API docs](https://github.com/aws/sagemaker-python-sdk/tree/master/doc) (if appropriate)

#### Tests

- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added unit and/or integration tests as appropriate to ensure backward compatibility of the changes
- [ ] I have checked that my tests are not configured for a specific region or account (if appropriate)
- [ ] I have used [`unique_name_from_base`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L77) to create resource names in integ tests (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-04 23:13 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=82cab7e1-e854-433d-80c1-7ba06f0906d2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-04 23:15 UTC, knikure reviewed
/bot run

2022-08-04 23:16 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=f5f0db91-fc70-4202-8208-b5ccb9be69e1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-04 23:19 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0ffd9c93-1476-44e1-a2bd-532593c6cfca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-04 23:44 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=2d541682-bc23-45db-a495-f41968676774%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 00:01 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d4a08436-9af5-4642-a5eb-6e0f8746cd43%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 00:07 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=de37f782-74df-4a1a-8ffb-eee8d87910ab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 00:21 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1a866af3-b920-44b7-a052-1c9d631f0437%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 21:30 UTC, navinsoni reviewed
/bot run abc

2022-08-05 21:35 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=08cd0e59-708d-45d2-acf5-c0e36dfb3fa1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 22:03 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5db0b590-9bd7-4502-92c8-78946fdfaf19%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 22:14 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fdc9f608-0531-4856-8533-1ae863fd821b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 22:17 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1b25f3bc-a509-41ad-89ca-12fd3659b8ce%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 22:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=da7936e8-bd4d-4b7f-80bd-f262f58652b2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 23:51 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=31edb83a-2a4a-4319-a657-824b485dbc3b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-05 23:56 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=bcb97b68-afb2-4bf2-a770-cb855dcb9553%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-06 00:18 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=40ff69f7-d508-4905-8081-566273db5dfa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-06 00:30 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ca34c0ed-1048-48b6-ab26-446f4f040644%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-06 00:36 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4fcee1d3-5fb0-4d2b-9d0b-28fd3baa0ddf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-06 01:48 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=122ed9ab-b497-4867-8d6a-596f665922d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 16:49 UTC, knikure reviewed
/bot run notebook-tests

2022-08-08 16:52 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=522b4c58-fd29-4ec5-9a40-173da94ff188%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 16:53 UTC, knikure reviewed
xnbfjh

2022-08-08 16:54 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=738c21c9-9891-4eb8-9429-12dff4c49b6b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 16:58 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=444d7294-863f-47f9-b781-fd2c1dddd1f7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 17:11 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b948aa5c-c029-4d96-b871-f512e95f6cf0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 17:18 UTC, knikure reviewed
dfdf

2022-08-08 17:20 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=c43def02-8aae-419e-a5b1-84ecc1f50cab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 17:49 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7bf38520-1878-4d79-a04e-080f7610e2c2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 17:55 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=360a2c5a-399d-4dda-b9ee-2a90a7d8219d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 18:01 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d11b17c5-5227-4eea-9f0f-40645c13a9dd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 18:38 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=9599d260-401c-4ada-a69a-cf1d624bcb30%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 17:52 UTC, knikure reviewed
gdhrgbkjjy

2022-08-09 17:54 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=624bb792-2fbd-4f0f-967c-b77b151685e0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 18:16 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=251ada71-f3fe-4149-9547-1a7ca9dba7b2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 18:18 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1f4a2dbf-0b36-43bf-9438-9d1f17a057c9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 18:30 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b37eba44-4b94-484b-b8fa-4067bccc16a8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 18:49 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=370d4b31-c638-44fd-8fb9-a4731e0dd4f9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 18:57 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=97a25354-4cbf-4eef-8a69-224a1a08e8d1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 19:08 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d88cff1e-fd21-4561-b07e-9b444dfc5bf6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 19:13 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3315b4b0-e472-4bd8-879e-066b247e0850%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 22:25 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fc920b5c-5890-4670-b644-df3d456bfcc5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 22:29 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=cc5dd139-6f2b-4798-a7e9-b0e0d37fcbd9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 22:40 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d879d2b0-e220-4d60-b51d-0ec03c5c0420%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 22:44 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=98a89b0e-fe03-4287-9f6f-0f966c40c73c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 23:12 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=9de2c49f-aaae-4b1e-ba87-9353ec9290b7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 23:24 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ba0d8bce-0f55-4583-8011-a9985bf6abd5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 23:28 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0172c088-7cbb-441a-8dc0-40537706d9ad%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 23:35 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=bedec789-0d14-4267-b9a6-353cde3b4f04%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 00:01 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=c6cb03f7-4b35-487d-abcc-53ec6445e836%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 00:28 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=2be9f48a-69a4-4176-8938-94442fe887fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 00:44 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=78306711-34dd-4ebd-b367-8a941bcaebd9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 00:47 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b0a334bc-f651-458a-ab1b-d8e595edec01%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 01:19 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ee11d878-50ae-41c0-9f16-96a80c6fca63%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 02:03 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b9a5702a-7d98-43d9-99a0-4bcc8645b9a1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 02:07 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=f8da0180-0ac9-421e-b058-b4a6f912ab73%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 02:27 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=9d5642d6-1d5f-4d81-9b29-99d799049b12%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 02:38 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=964f90d0-98ea-4bc9-876d-5e514734312b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 02:42 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1311e0df-302c-42d0-b1a0-1d242f8d5ccd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 01:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=65f65f8d-ccd4-43bf-b3dc-fc2146b2659b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 01:26 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7ab26ce8-cc38-4ac9-b71f-45b80ef2fb30%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 01:35 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5ba293f1-244d-462d-86fa-d88f1dbb64cc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 01:38 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=dad16686-44a4-4860-95f4-69d44e6aa188%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 02:05 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=00b68abd-38c9-45b9-8b99-acaecded2a76%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 02:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=a551f6f0-7f6f-410e-b642-ace7f2b0bb3a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 02:28 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=18a4dac1-8317-4326-a141-c4041a795a0e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 02:31 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=362e83ae-200b-4cde-9a6d-0b8acd9608bf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 17:19 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=8f86a780-124c-4979-ad01-a31e1a094f7b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 17:20 UTC, knikure reviewed
/bot run all

2022-08-12 17:24 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=9dd15e17-4d7f-4ae7-8326-a3539ad8f3b2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 17:24 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=a28915b1-021b-4db3-afa5-60b1ecaa1e96%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 17:33 UTC, ekinfu22 reviewed
/bot run pr

2022-08-12 17:53 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=8383749e-290c-4b8b-9a31-89a904d6f609%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 18:01 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=64e5c179-575d-4bcc-b6ef-fa7552f14b76%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 18:47 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b522d615-773c-4818-ae83-869daaf95934%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 22:03 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=70d0feaf-94ab-4070-b948-b073f073d764%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 22:08 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=767ca988-0f96-4ab3-93fd-2e4d1a69a2cf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 22:15 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4e233f2d-046f-4bc7-9f4a-37268f64bc13%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 22:43 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3eef2303-be9b-486e-8422-a7f0e0ffc1ac%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 23:00 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=019e9c3a-9681-4f5f-ad19-31374932ee85%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 23:05 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=40ba930d-76ff-4457-837f-5976b4b8aed2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 23:19 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=aeb4dad8-debf-42ed-be7b-f5ae1954e871%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 17:31 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=efa788e1-1706-40db-ba6b-c5c41c8ed5f7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 17:39 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=2378927c-d657-404b-9b35-954263f7bfc5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 17:41 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=867bf2af-a7c6-4d54-a5f9-9f6fde85948c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 17:57 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=9227801b-b274-4957-981d-3aea3cc8b6c8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 18:03 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=2fa16537-342d-429e-aba0-df3b6539289c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 18:08 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=39ec0721-f1fa-4c93-be01-076416c6e8bd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 18:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=412b03fc-ff68-4a1e-87b5-c54342573821%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 18:33 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=c1f17bde-374d-4ca8-9d57-923e7f728a9a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 18:37 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1a7d8cf0-413e-4101-84e6-171d7f3202ee%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 18:39 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ebc2a6c8-dda2-47e1-840d-fb5f37ea2db0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 18:43 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3c55e711-4c46-4f29-9b0b-e961f137fece%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 19:07 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1768c99c-7465-45b5-ac76-d9fedcfaa1a0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 19:25 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=62c2adb1-50d7-4df8-95d5-0c9806c38f58%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 19:38 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=931c7cda-b913-4c53-85a9-8d630108c352%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 20:18 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=35fdb7fa-74b6-4c38-85f7-92d474d72f1b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 20:59 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4b6bbdcb-d99e-4bba-8f2b-ad3a851d0980%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 21:05 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=701f7359-f231-45d4-8ec2-b4aba568f409%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 21:24 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0bb1ad00-81a1-4897-9c1d-1d7f7ec0e848%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 21:33 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d0ae9d14-91a2-476e-97ab-ad5ba10b6506%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 22:01 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1dbb9d0c-dd21-4aa8-ab7d-f37c0bbe46b6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 22:14 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d1fc6ec6-567c-44dd-97b9-bbdd6c917894%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 22:21 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=695ba011-da65-4826-b73d-33689e9b45b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 22:21 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=14bbc087-8014-486e-8c65-d7245cd5f7f1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 00:23 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b21f475e-4f34-47d7-a9f3-e434e995aca9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 00:51 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=010a50f5-30ff-47a0-ba65-dda5aa851707%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 01:05 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=aac2d743-0410-4515-965f-9c7f499562e8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 01:11 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ae0c19ed-05ca-4248-b373-9667d01e083c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 01:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=8346e083-6b4f-432d-96f4-be23c17c0ca0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 18:41 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=2a5c64f4-4dc2-4d15-8ea1-617af387742d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 19:17 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=27aaf3bb-5eb4-482a-a238-9fa6d3749405%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 20:30 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7789461b-eb28-4628-b199-769b06bf511f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 20:49 UTC, knikure reviewed
test comment

2022-08-18 20:49 UTC, knikure reviewed
/bot run

2022-08-18 20:50 UTC, knikure reviewed
/bot run pr

2022-08-18 20:50 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=f40a5470-0673-43c9-9b7c-637da984d923%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 20:51 UTC, knikure reviewed
/bot run pr, slow-tests, notebook-tests

2022-08-18 20:52 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1185e140-3911-45ed-88db-5470a3039d2e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 21:05 UTC, knikure reviewed
/bot run pr1

2022-08-18 21:05 UTC, knikure reviewed
/bot run pr, unit, notebook-tests, local

2022-08-18 21:08 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=12b7f469-ca60-4598-9df3-b5f212960046%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 21:17 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ae6ce24a-7a4d-4908-984e-b16528ea54fe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 21:30 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fa5e7da9-8aef-429f-8706-93673c7892a7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 22:13 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5ee554ea-d11e-4ad4-8d2f-fd01c4b7046f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 22:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3d8af2f3-86f1-4345-9924-0abd572cf1dc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-19 00:21 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=cfb604d5-18ff-4828-9a49-3d20e5e39b17%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-19 00:37 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=89b2d506-0fef-4fa2-86a3-e5a07168ea7e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-19 00:46 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0549e84d-c902-4850-ad74-febccd0567a0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-19 01:07 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4a363270-4045-42af-9930-b2ae94b058c0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-19 01:11 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=01e562bc-b97c-483e-a845-bbce45b2de91%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-19 01:20 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=77213ffc-064c-4346-b638-0b1d129f3ede%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 17:47 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=a79624a4-a4df-42a4-b278-69638e748365%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 17:50 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=516c40ca-b87a-4817-8528-ab22b1e3cdae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 17:56 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=8bac712b-b81e-4bb5-8306-eac075f2f4b3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 18:04 UTC, mufaddal-rohawala approved these changes

2022-08-29 18:24 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=2e020b6b-c593-47bf-8b41-a3e41b884722%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 18:40 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=31bdd523-d05a-4aa9-9a50-1d10f79cb383%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 19:10 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5749c456-a461-455e-99b7-1319913d97ab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 19:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4b111b0e-45e2-49e1-9814-8ceeaae9cd34%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 20:04 UTC, claytonparnell requested changes
Test comment

2022-08-29 20:04 UTC, claytonparnell approved these changes
Review changes

2022-08-29 20:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1e9f516b-5928-4b9a-b967-8b1862c3e302%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 20:50 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=03d2ee52-8952-4771-9c19-b4bd10736180%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 21:06 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=c59fc8d3-2427-4180-bda8-f7d501da54ba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 21:17 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4a5991ba-c71d-4ced-915b-ecba1e10435f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 21:22 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=69ffca66-a477-4aeb-bfb5-0225b395e943%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 16:46 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=62c802ef-f3cb-4615-b708-1d5db99d9498%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 17:04 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7a4f8330-256d-42d1-835f-b38cbcf61b48%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 17:06 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=a8eb03cb-461b-4e4a-97fd-6310202df3f0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 17:20 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=2bf2f2df-d1b7-43e9-afed-2554b00452b2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 17:37 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=84be2d0d-175c-4a06-b09a-593bf1dad2d7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 17:48 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4d77b9a9-b6c9-46b4-807b-353e4b3dd0af%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 18:04 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1d1f3526-26c9-497d-8bd0-d8dcc1cdd072%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 18:06 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=47c68fed-94dd-4011-aecf-f8441df599b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-23 17:23 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7fb9b8d6-3af4-4c0a-83fb-9f73c51bcc5b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-23 19:29 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5ae4e531-274e-4daa-a892-7636c24d9956%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:01 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://qe3q6ius9i.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7d5282a1-80cf-4613-8b5b-0dca6dfda0b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:01 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-notebook-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://3vcwi2fhc6.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7d5282a1-80cf-4613-8b5b-0dca6dfda0b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:29 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://zgbm0ods4a.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4622f4b6-98b8-433a-8a57-7ba2bf092720%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:29 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-unit-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://1eku8kz63g.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4622f4b6-98b8-433a-8a57-7ba2bf092720%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:42 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://wz6xmsyiyb.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=66c64c95-186d-4646-94c1-6bb8390f4539%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:42 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-local-mode-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: SUCCEEDED
* [Build Logs](https://uah08swvz4.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=66c64c95-186d-4646-94c1-6bb8390f4539%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:54 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://kwi4pk9ncd.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d03dba07-097c-40ca-9347-e433ae9eee67%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 21:54 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: knikure-sagemaker-python-sdk-pr
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://18o4jkfmeg.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d03dba07-097c-40ca-9347-e433ae9eee67%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 22:18 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://ycryrlx7yl.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=03f895c4-22d7-4b16-829a-9dfd94906b87%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 22:18 UTC, knikure commented
### AWS CodeBuild CI Report

* CodeBuild project: sagemaker-python-sdk-slow-tests
* Commit ID: 69c6e2912cfb05cb8e52e65273e1eea595ea93be
* Result: FAILED
* [Build Logs](https://jrh02j7dci.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=03f895c4-22d7-4b16-829a-9dfd94906b87%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-22 20:33 UTC, closed without merging